In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

# model = AutoModelForCausalLM.from_pretrained(
#     model_name,
#     torch_dtype="auto",
#     device_map="auto"
# )
tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
# model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

# generated_ids = model.generate(
#     **model_inputs,
#     max_new_tokens=512
# )
# generated_ids = [
#     output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
# ]

# response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]


tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [2]:
text

'<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nGive me a short introduction to large language model.<|im_end|>\n<|im_start|>assistant\n'

In [4]:
import torch

x = torch.arange(5)

In [5]:
y = torch.randn(10,4)

In [6]:
y

tensor([[-5.9837e-01, -7.0353e-01, -3.5719e-01, -1.1586e+00],
        [ 1.7654e+00, -1.1997e+00, -4.1497e-01, -5.4547e-01],
        [-1.0796e+00,  1.7726e+00, -1.2707e+00, -9.3302e-01],
        [ 1.8305e+00,  2.9170e+00,  5.6828e-02,  2.5530e-01],
        [ 1.9603e+00, -1.0589e+00, -7.8571e-02, -1.4501e-01],
        [ 1.3621e+00,  1.8107e-01, -1.7502e-03, -1.9096e+00],
        [-7.4161e-01,  2.2433e+00,  5.6576e-01,  6.0646e-01],
        [ 1.1309e+00,  2.6344e-02, -6.3389e-01,  8.1797e-02],
        [ 1.9896e+00, -3.6213e-01, -1.4316e-01, -4.1553e-01],
        [-3.6178e-01, -5.2421e-02, -3.0385e-01, -1.0518e+00]])

In [7]:
y[x,]

tensor([[-0.5984, -0.7035, -0.3572, -1.1586],
        [ 1.7654, -1.1997, -0.4150, -0.5455],
        [-1.0796,  1.7726, -1.2707, -0.9330],
        [ 1.8305,  2.9170,  0.0568,  0.2553],
        [ 1.9603, -1.0589, -0.0786, -0.1450]])

In [8]:
y[[0,1,2,3,4],]

tensor([[-0.5984, -0.7035, -0.3572, -1.1586],
        [ 1.7654, -1.1997, -0.4150, -0.5455],
        [-1.0796,  1.7726, -1.2707, -0.9330],
        [ 1.8305,  2.9170,  0.0568,  0.2553],
        [ 1.9603, -1.0589, -0.0786, -0.1450]])

In [9]:
from transformers import AutoTokenizer 

tok = AutoTokenizer.from_pretrained("meta-llama/Llama-3.1-8B")

loading file tokenizer.json from cache at /home/donggunseo/.cache/huggingface/hub/models--meta-llama--Llama-3.1-8B/snapshots/d04e592bb4f6aa9cfee91e2e20afa771667e1d4b/tokenizer.json
loading file tokenizer.model from cache at None
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at /home/donggunseo/.cache/huggingface/hub/models--meta-llama--Llama-3.1-8B/snapshots/d04e592bb4f6aa9cfee91e2e20afa771667e1d4b/special_tokens_map.json
loading file tokenizer_config.json from cache at /home/donggunseo/.cache/huggingface/hub/models--meta-llama--Llama-3.1-8B/snapshots/d04e592bb4f6aa9cfee91e2e20afa771667e1d4b/tokenizer_config.json
loading file chat_template.jinja from cache at None
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [10]:
tok.encode(" "+"card_arrival"+"\n\n"+tok.eos_token, add_special_tokens = False)

[3786, 11459, 4023, 271, 128001]

In [14]:
import random

z = [1, 2,3,4,5,6]

zp = random.sample(z,2)

In [16]:
random.choice(z)

5